# Generated by Django 2.0 on 2017-12-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geupsikbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lunch', models.CharField(default='', max_length=150)),
                ('dinner', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
