# Generated by Django 2.0 on 2017-12-18 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geupsikbot', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.date(2017, 12, 19)),
        ),
    ]
